name: shorty

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: php83_apache_server
    ports:
      - "801:80"
      - "4431:443"
    volumes:
      - ../:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: laraveluser
      DB_PASSWORD: your_laravel_db_password

  db:
    image: mysql:8.0
    container_name: mysql_server
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: your_laravel_db_password
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: