name: shorty

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: php83_apache_server
    ports:
      - "801:80"
      - "4431:443"
      # Vite
      - "3000:3000"
    volumes:
      - ../:/var/www/html
    # Set Laravel folder permissions
    command: bash -c "chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache && chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache && apache2-foreground"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: shorty
      DB_USERNAME: root
      DB_PASSWORD: root

  db:
    image: mysql:8.0
    container_name: mysql_server
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: shorty
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # Volumes can be purged via Docker Desktop
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
